import { Button } from "@/components/ui/button";
import { UAParser } from "ua-parser-js";

// Generated by https://iplogger.org/useragents/
const DUMMY_USER_AGENT = [
  "Mozilla/5.0 (Windows NT 10.1;) AppleWebKit/534.19 (KHTML, like Gecko) Chrome/47.0.1581.289 Safari/600.1 Edge/8.37086",
  "Mozilla/5.0 (Linux; U; Android 5.0.1; SAMSUNG SM-T555 Build/LRX22G) AppleWebKit/533.8 (KHTML, like Gecko) Chrome/54.0.2530.150 Mobile Safari/601.4",
  "Mozilla/5.0 (compatible; MSIE 9.0; Windows; U; Windows NT 6.1; Win64; x64; en-US Trident/5.0)",
  "Mozilla/5.0 (Linux; Linux i653 x86_64; en-US) AppleWebKit/603.37 (KHTML, like Gecko) Chrome/52.0.2985.245 Safari/535",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 9_4_1; like Mac OS X) AppleWebKit/603.7 (KHTML, like Gecko) Chrome/53.0.3384.344 Mobile Safari/602.2",
];
export default function SessionSection() {
  return (
    <section>
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <h2 className="text-lg font-medium">Sessions</h2>
          <p className="text-sm font-light">
            Manage your active sessions and revoke access to your account.
          </p>
        </div>
        <Button size="sm" variant="destructive">
          Revoke All
        </Button>
      </div>
      <ul className="mt-5 divide-y divide-solid">
        {DUMMY_USER_AGENT.map((ua, index) => (
          <SessionItem key={index} ua={ua} lastActive={new Date()} />
        ))}
      </ul>
    </section>
  );
}

interface SessionItemProps {
  ua: string;
  lastActive: Date;
}
function SessionItem(props: SessionItemProps) {
  const { os, browser } = new UAParser(props.ua).getResult();

  return (
    <li className="py-3">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm">
            {browser.name} on {os.name}
          </p>
          <p className="text-xs font-light">Last active 2 hours ago</p>
        </div>
        <Button size="sm" variant="outline">
          Revoke
        </Button>
      </div>
    </li>
  );
}
